# Generated by Django 3.1.7 on 2021-04-09 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='タイトル')),
                ('comment', models.CharField(max_length=2000, verbose_name='動画説明文')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
