# Generated by Django 3.1.7 on 2021-04-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
