# Generated by Django 3.1.7 on 2021-04-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0003_video_dt2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='dt2',
        ),
    ]
