# Generated by Django 3.1.7 on 2021-04-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_video_dt2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='dt2',
        ),
        migrations.AddField(
            model_name='video',
            name='update_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='最終更新日'),
        ),
    ]
