# Generated by Django 3.1.7 on 2021-04-17 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0006_auto_20210417_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEdited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最終更新日')),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='update_dt',
        ),
    ]
