# Generated by Django 3.1.7 on 2021-04-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0007_auto_20210417_1942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoEdited',
        ),
    ]
