# Generated by Django 3.1.2 on 2021-04-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0009_auto_20210421_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='movie',
            field=models.FileField(blank=True, upload_to='tube/movie/', verbose_name='動画'),
        ),
    ]
