# Generated by Django 3.1.2 on 2021-04-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0010_auto_20210421_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='movie',
        ),
        migrations.AddField(
            model_name='video',
            name='pdf',
            field=models.FileField(blank=True, upload_to='tube/pdf/', verbose_name='PDF'),
        ),
    ]
